global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'spring boot'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'My Spring Boot Application'

  # - job_name: 'node-exporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']
