management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans
      base-path: /actuators

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: "My application in Spring"
